import Head from "next/head";
import { Inter } from "next/font/google";
import Landing from "@/components/Landing/Landing";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mizu | Home</title>
        <meta name="description" content="Generated by Ouaklim" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Landing />
      </main>
    </>
  );
}
